CREATE TABLE product_types(
	name TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE product(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL,
	type TEXT NOT NULL,
	unit TEXT NOT NULL,

	FOREIGN KEY (type) REFERENCES product_types(name) ON UPDATE CASCADE
);

CREATE TABLE user(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	username TEXT NOT NULL,
	surname TEXT NOT NULL,
	name TEXT NOT NULL,
	password TEXT NOT NULL,
	vegetarian INT NOT NULL,
	email TEXT NOT NULL,
	latitude REAL NOT NULL DEFAULT 50.850346,
	longitude REAL NOT NULL DEFAULT 4.351721
);

CREATE TABLE recipe(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL,
	user INT NOT NULL,
	description TEXT NOT NULL,
	dish_type TEXT NOT NULL,
	number_people INT NOT NULL,

	FOREIGN KEY (user) REFERENCES user(id) ON UPDATE CASCADE
);

CREATE TABLE recipe_list(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	recipe INT NOT NULL,
	product INT NOT NULL,
	quantity REAL NOT NULL,

	FOREIGN KEY (recipe) REFERENCES recipe(id) ON UPDATE CASCADE,
	FOREIGN KEY (product) REFERENCES product(id) ON UPDATE CASCADE
);

CREATE TABLE shopping_list(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL,
	date DATE NOT NULL,
	user INT NOT NULL,
	archivised INTEGER NOT NULL,

	FOREIGN KEY (user) REFERENCES user(id) ON UPDATE CASCADE
);

CREATE TABLE products_list(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	list INT NOT NULL,
	product int NOT NULL,
	quantity REAL NOT NULL,

	FOREIGN KEY (list) REFERENCES shopping_list(id) ON UPDATE CASCADE, 
	FOREIGN KEY (product) REFERENCES product(id) ON UPDATE CASCADE
);
CREATE TABLE day_planning(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	date TEXT NOT NULL,
	user id NOT NULL,
	
	FOREIGN KEY (user) REFERENCES user(id)
);
CREATE TABLE recipes_to_day(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	day int NOT NULL,
	recipe int NOT NULL,
	guests_count int NOT NULL,
	
	FOREIGN KEY (day) REFERENCES day_planning(id),
	FOREIGN KEY (recipe) REFERENCES recipe(id)
);
